# Generated by Django 4.0.6 on 2022-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=18),
        ),
    ]
