# Generated by Django 4.0.6 on 2022-07-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_refeicao_opcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.paciente'),
        ),
    ]
